# 공통
spring:
  profiles:
    active: local
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
---
# LOCAL
server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:h2:file:./h2db/restaurant
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
---

logging:
  level:
    org.springframework.jdbc.datasource.SimpleDriverDataSource: DEBUG
    org.hibernate.SQL: DEBUG